name: Cypress Tests

on: [push]

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run: npm run test
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir -p public/$(date +%Y)/$(date +%m)
          cp -r cypress/videos public/$(date +%Y)/$(date +%m)/videos
          cp -r cypress/screenshots public/$(date +%Y)/$(date +%m)/screenshots
          cp -r cypress/reports/html/* public/$(date +%Y)/$(date +%m)/

      - name: indexing Files
        run: npm run index-tests
      # - name: Merge test reports
        # run: npm run combine:report

     # - name: Generate HTML report
     #   run: npm run generate:report
      
      - name: Deploy report page to GitHub Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./public
